language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

branches:
  except:
    - gh-pages

before_script:
  - "mysql -e 'create database `social_testing`;'"
  - composer install -n --prefer-source
  - php artisan migrate --seed -n
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run